### ISSUE TITLE
code for index.js 

### ISSUE THREAD

**Issue by RobCraftNet** [Bjornskjald/messenger-discord#58]
messenger-discord-master\index.js:29
  if (message.channel.parent.name !== config.discord.category.name) return
                             ^

TypeError: Cannot read property 'name' of null
    at Client.discordListener (C:\Users\robbi\Downloads\messenger-discord-master\messenger-discord-master\index.js:29:30)
    at Client.emit (events.js:160:13)
    at MessageCreateHandler.handle (C:\Users\robbi\Downloads\messenger-discord-master\messenger-discord-master\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\robbi\Downloads\messenger-discord-master\messenger-discord-master\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\robbi\Downloads\messenger-discord-master\messenger-discord-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (C:\Users\robbi\Downloads\messenger-discord-master\messenger-discord-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:293:17)
    at WebSocket.onMessage (C:\Users\robbi\Downloads\messenger-discord-master\messenger-discord-master\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:160:13)
    at Receiver._receiver.onmessage (C:\Users\robbi\Downloads\messenger-discord-master\messenger-discord-master\node_modules\ws\lib\websocket.js:145:47)
    at Receiver.dataMessage (C:\Users\robbi\Downloads\messenger-discord-master\messenger-discord-master\node_modules\ws\lib\receiver.js:430:14)
    at Receiver.getData (C:\Users\robbi\Downloads\messenger-discord-master\messenger-discord-master\node_modules\ws\lib\receiver.js:368:12)
    at Receiver.startLoop (C:\Users\robbi\Downloads\messenger-discord-master\messenger-discord-master\node_modules\ws\lib\receiver.js:164:16)
    at Receiver.add (C:\Users\robbi\Downloads\messenger-discord-master\messenger-discord-master\node_modules\ws\lib\receiver.js:138:10)
    at TLSSocket._ultron.on (C:\Users\robbi\Downloads\messenger-discord-master\messenger-discord-master\node_modules\ws\lib\websocket.js:143:54)
    at TLSSocket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! messenger-discord@2.4.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the messenger-discord@2.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\robbi\AppData\Roaming\npm-cache\_logs\2018-02-23T01_17_16_963Z-debug.log

**Comment by Bjornskjald** [comment]
sorry, it has been fixed in #57 (version 2.4.2) so just download the newest version from Github
