### ISSUE TITLE
Unable to "npm start"

### ISSUE THREAD

**Issue by talormanda** [Bjornskjald/messenger-discord#62]
I run all the steps, after "cd messenger-discord" and "npm start", I get:
```javascript
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.21
3 info using node@v4.8.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart messenger-discord@2.4.2
6 info start messenger-discord@2.4.2
7 verbose unsafe-perm in lifecycle true
8 info messenger-discord@2.4.2 Failed to exec start script
9 error messenger-discord@2.4.2 start: `node index.js`
9 error Exit status 1
10 error Failed at the messenger-discord@2.4.2 start script.
10 error This is most likely a problem with the messenger-discord package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node index.js
10 error You can get their info via:
10 error     npm owner ls messenger-discord
10 error There is likely additional logging output above.
11 error System Linux 4.9.59-v7+
12 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
13 error cwd /home/pi/messenger-discord
14 error node -v v4.8.2
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]
```
----------------------------------
Updated to node 9.6.1, ran "npm install", then "npm start" and now I get this:
```javascript
pi@pi3_raspbian:~ $ cd messenger-discord/
pi@pi3_raspbian:~/messenger-discord $ sudo npm start

> messenger-discord@2.4.2 start /home/pi/messenger-discord
> node index.js

Error:
{ DiscordAPIError: Missing Permissions
    at item.request.gen.end (/home/pi/messenger-discord/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/pi/messenger-discord/node_modules/snekfetch/src/index.js:213:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  name: 'DiscordAPIError',
  message: 'Missing Permissions',
  path: '/api/v7/guilds/340905584423469056/channels',
  code: 50013 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! messenger-discord@2.4.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the messenger-discord@2.4.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-25T17_10_30_812Z-debug.log

```

**Comment by Bjornskjald** [comment]
Could you show me the output of `node -v`?
I think you're running too old version of node

**Comment by Bjornskjald** [comment]
Did the script say something except the path to the log file?

**Comment by talormanda** [comment]
I updated to node 9.6.1 , I get a new error. See the original post for this.

**Comment by talormanda** [comment]
Edit: I gave it admin permission on the discord apps webpage and readded it, and it now works. Thanks!

**Comment by talormanda** [comment]
Resolved!
